### PR TITLE
NO_MERGE [maven-release-plugin] prepare release parameterized-trigger-2.35.2

### PR DESCRIPTION
**Pull request by GLundh**
We have a few small but very important fixes on master. Perhaps we can release 2.35.2?

### CODE REVIEW

**Comment by kwhetstone** [comment]
I can do the release, I'll wait until the end of the day in case we have anything else we'd like to merge.

**Comment by kwhetstone** [comment]
I'll do the release myself and close this.  Do we want to look at #104 before merging?

**Comment by GLundh** [comment]
Thanks for prompt response! Really appreciate it!

**Comment by GLundh** [comment]
How is the release going? I know you guys have been busy with Jenkins World and stuff. Anything I can do to help getting the release out of the door?

**Comment by kwhetstone** [comment]
Released the new version.  It should be available through the update center in a few hours.  Thanks!

**Pull request closed without merging**
