### PR TITLE
[FIXED JENKINS-31727] - ConfigTrigger should be tolerant against Item.DISCOVER without Item.READ

### PR DESCRIPTION
**Pull request by oleg-nenashev**
In https://issues.jenkins-ci.org/browse/JENKINS-31727 the issue happens due to the explicit usage of Item.DISCOVER w/o Item.READ. Groovy UIs trigger AccessDeniedException, which finally leads to the UI corruption.

During the fix I've also adjusted implementations of other Getter methods in order to avoid failures.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @svanoort

**Comment by alecharp** [comment]
:bee:

**Comment by Vlatombe** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by svanoort** [comment]
:+1:  and merging as a pseudo-maintainer.  

Note that the try/catch use here to check for access is somewhat expensive due to creation of Exceptions.  For now that's fine, but if people report performance issues, we may want to look at a direct permission check for that, as cheaper than trying it and getting an exception.

**Pull request merged**
