### PR TITLE
Add an ability to pass build parameters to post build trigger

### PR DESCRIPTION
**Pull request by sshelomentsev**
Ability to pass build parameters in the post-build action 'Trigger parameterized build on other projects'.
Like ${bugID}/assembly, which ${bugID} is a string build parameter.
Also, I've added actions to job and build that shows a list of downstream projects that passed with parameters.

screen shot 2016-04-21 at 7 55 36 pm
screen shot 2016-04-21 at 7 55 27 pm

### CODE REVIEW

**Comment by sshelomentsev** [comment]
Test Result (1 failure / +1)
hudson.plugins.parameterizedtrigger.test.SubversionRevisionBuildTriggerConfigTest.testRevisionParameter

This test fails local assembly of the master branch. I believe this is not an issue of the current pull-request.

**Comment by ad22** [comment]
This pull request should fix the failing unit test: https://github.com/jenkinsci/parameterized-trigger-plugin/pull/101

**Comment by sshelomentsev** [comment]
Hi @oleg-nenashev 
Can you please review this?

**Comment by sshelomentsev** [comment]
This PR merged with the original master branch.
Could you please, guys @svanoort @huybrechts review this when you get a chance?

**Comment by kwhetstone** [comment]
This looks fine, I'll merge it in.

**Pull request merged**
