### PR TITLE
[FIXED JENKINS-26031] Added export of triggered builds to XML/JSON API

### PR DESCRIPTION
**Pull request by abayer**

### CODE REVIEW

**Comment by ikedam** [comment]
I don't think this work as expected.

**Comment by wolfs** [comment]
Replaced by #82.

**Comment by mthak** [comment]
How do i get the same data using XML . I don't see it exposed via api/xml, i do see it in json though

**Comment by wolfs** [comment]
<jenkins-url>/job/<job-name>/<build-id>/api/xml?depth=1 works like a charm for me.

**Pull request closed without merging**
