### PR TITLE
JENKINS-64502 Fix plugin on Jenkins >=2.264

### PR DESCRIPTION
**Pull request by timja**
https://issues.jenkins.io/browse/JENKINS-64502

cc @olamy

### CODE REVIEW

**Comment by timja** [comment]
A user of this plugin has tested it and reported the bug fixed by this PR:
https://issues.jenkins.io/browse/JENKINS-64502?focusedCommentId=402673&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-402673

**Review by oleg-nenashev — APPROVED** [review]
We are already at 2.270+, so looks like this s the best way

**Review by olamy — APPROVED** [review]

**Comment by Panajev** [comment]
Hello @oleg-nenashev  @olamy  has this been released? Referrring to: https://issues.jenkins.io/browse/JENKINS-62913

**Comment by timja** [comment]
release in https://github.com/jenkinsci/parameterized-trigger-plugin/releases/tag/parameterized-trigger-2.40

see https://issues.jenkins.io/browse/JENKINS-64502

**Pull request merged**
