### PR TITLE
[JENKINS-32527] Handle null @AncestorInPath when selecting Downstream…

### PR DESCRIPTION
**Pull request by Dohbedoh**
… Jobs

@reviewbybees Same as JENKINS-32525 and JENKINS-32526

I added some field validation tests for the `doCheckProjects` methods

### CODE REVIEW

**Comment by Dohbedoh** [comment]
@reviewbybees Fix similar to: 
- https://github.com/jenkinsci/jenkins/commit/85365c6f399cd3dcdc9a0c10fb6737e4d9a3e5ca
- https://github.com/jenkinsci/copyartifact-plugin/commit/a34592bc7bfd3d733da7d520f6c15dbc6b728043

**Comment by Evildethow** [comment]
🐝

**Comment by jglick** [comment]
:bee:

**Comment by Dohbedoh** [comment]
@huybrechts It's been 6 months already, can we merge this?

**Comment by Dohbedoh** [comment]
@reviewbybees done

**Comment by kwhetstone** [comment]
@Dohbedoh it looks like this needs to be merged in.  Could you address the conflicting file, and I'll be able to merge it in?

**Comment by Dohbedoh** [comment]
@kwhetstone Sorry for the delay. All done, I rebased to master.

**Comment by kwhetstone** [comment]
Awesome!  I'll merge this and you can close the Jenkins ticket.

**Pull request merged**
